@ContosoPizza_HostAddress = http://localhost:5160

GET {{ContosoPizza_HostAddress}}/weatherforecast/
Accept: application/json

GET {{ContosoPizza_HostAddress}}/api/mytest/
Accept: application/json

GET {{ContosoPizza_HostAddress}}/pizza/
Accept: application/json 

GET {{ContosoPizza_HostAddress}}/pizza/{id}
Accept: application/json

GET {{ContosoPizza_HostAddress}}/pizza/count/
Accept: application/json

###
